team_number: 1

kafka:
  broker_ip: "10.144.101.19:9092"
  topics:
    cpu: "topic-cpu"
    mem: "topic-mem"
    net: "topic-net"
    disk: "topic-disk"

producer:
  producer_ip: "10.144.115.47"

consumers:
  consumer1_ip: "10.144.174.14"
  consumer2_ip: "10.144.115.215"

spark_jobs:
  window_duration: "30 seconds"
  slide_duration: "10 seconds"

alert_thresholds:
  cpu_pct: 94.35
  mem_pct: 78.06
  net_in: 4724.68
  disk_io: 4563.25

paths:
  data_file: "data/dataset.csv"
  output_dir: "output/"
